package types

const ONE_BYTE = 1
const ONE_KILOBYTE = 1024 * ONE_BYTE
const ONE_MEGABYTE = 1024 * ONE_KILOBYTE
const ONE_GIGABYTE = 1024 * ONE_MEGABYTE
const ONE_TERABYTE = 1024 * ONE_GIGABYTE
const ONE_PETABYTE = 1024 * ONE_TERABYTE

const SEGMENT_SIZE = 64 * ONE_MEGABYTE
